config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :time_threads do
    resources :time_posts, module: :time_threads
  end

  resources :users do
    collection do
      post :import
    end
  end

  root to: "time_threads#index"
end

app/models/time_post.rb
class TimePost < ActiveRecord::Base
  belongs_to :time_thread
  belongs_to :user

  validates :month, presence: true
  #validates_numericality_of :month, greater_than: 0
  #validates_numericality_of :month, less_than: 13
  validates :day, presence: true
  validates :minute, presence: true

  def user
    User.unscoped { super }
  end
end

app/models/time_thread.rb
class TimeThread < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :user
  has_many :time_posts
  has_many :users, through: :time_posts

  accepts_nested_attributes_for :time_posts

  validates :student_name, presence: true
  validates_associated :time_posts
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_paranoid

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable

  validates :email, presence: true

  has_many :time_threads
  has_many :time_posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/time_threads/time_posts_controller.rb
class TimeThreads::TimePostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_time_thread

  def create
    @time_post = @time_thread.time_posts.new time_post_params
    @time_post.user = current_user

    if @time_post.save
      #@forum_post.send_notifications!
      redirect_to time_thread_path(@time_thread, anchor: "time_post_#{@time_post.id}"), notice: "Successfully posted!"
    else
      redirect_to @time_thread, alert: "Unable to save your post"
    end
  end

  private

    def set_time_thread
      @time_thread = TimeThread.find(params[:time_thread_id])
    end

    def time_post_params
      params.require(:time_post).permit(:month, :day, :minute)
    end
end

app/controllers/time_threads_controller.rb
class TimeThreadsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_time_thread, except: [:index, :new, :create]

  def index
    @q = TimeThread.search(params[:q])
    @time_threads = @q.result(distinct: true)
  end

  def show
    @time_post = TimePost.new
  end

  def new
    @time_thread = TimeThread.new
    @time_thread.time_posts.new
  end

  def create
    @time_thread = current_user.time_threads.new time_thread_params
    #@time_thread.time_posts.first.user_id = current_user.id

    if @time_thread.save
      redirect_to @time_thread
    else
      render action: :new
    end
  end

  private

    def set_time_thread
      @time_thread = TimeThread.find(params[:id])
    end

    def time_thread_params
      params.require(:time_thread).permit(:student_name, time_posts_attributes: [:month, :day, :minute])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeacherForum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "shared/navbar" %>
  <div class="container">
  <%= yield %>

  </div>
  <!--<%= debug(params) if Rails.env.development? %>-->
</body>
</html>

app/views/shared/_navbar.html.erb
<header class="navbar <%= content_for?(:navbar_style) ? yield(:navbar_style) : "navbar-default" %> navbar-static-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_url, class: "navbar-brand" do %>
        Time records
      <% end %>
    </div>

    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li><%#= link_to "Threads", time_threads_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/time_posts/_form.html.erb
<%= form_for [@time_thread, @time_post] do |f| %>
  <div class="form_group">
    <%= f.text_field :month, placeholder: "month", class: "form-control" %>
    <%= f.text_field :day, placeholder: "day", class: "form-control" %>
    <%= f.text_field :minute, placeholder: "minute", class: "form-control" %>
  </div>
  <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/time_posts/_time_post.html.erb
<%= div_for time_post do %>
  <p class="text-muted">Posted by <%= time_post.id %> <%= local_time_ago time_post.created_at %></p>
  <p><%= time_post.month %></p>
  <p><%= time_post.day %></p>
  <p><%= time_post.minute %></p>
<% end %>

app/views/time_threads/_form.html.erb
<%= form_for @time_thread do |f| %>
  <div class="form-group">
    <%= f.text_field :student_name, placeholder: "student name", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/time_threads/_time_thread.html.erb
<%= link_to time_thread do %>
  <h3><%= time_thread.student_name %></h3>
<% end %>

app/views/time_threads/index.html.erb
<div class="container">
  <div class="pull-right">
    <%= link_to "Submit student time", new_time_thread_path, class: "btn btn-success" %>
  </div>

  <h1 class="page-header">Time Threads</h1>
  <%= render @time_threads %>
</div>

app/views/time_threads/new.html.erb
<h2>New Time</h2>

<%= render "form" %>

app/views/time_threads/show.html.erb
<h3><%= @time_thread.student_name %></h3>
<p class="text-muted">Created by <%= @time_thread.user_id %></p>
<%= render @time_thread.time_posts %>

<hr />
<%= render partial: "time_posts/form" %>